### ISSUE TITLE
iOS客户端上无法使用配置

### ISSUE THREAD

**Issue by 2huYa0** [dylanbai8/V2Ray_ws-tls_Website_onekey#1]
作者，您好~
有个问题想请教一下您，我用阁下的一键命令配置完V2Ray，在PC上V2RayN上使用正常，而在iOS上两个客户端（ShadowRocket和Kitsunebi）都无法正常使用，有办法可以调试一下吗？

**Comment by dylanbai8** [comment]
是不是 path 和 http header 没有配置正确? 直接导入 json 文件尝试一下 。如果还是不行，有可能这两个客户端目前还不支持 http header 分流？

**Comment by 2huYa0** [comment]
应该是iOS段不支持 http header 分流这个原因，用安卓端的V2RayNG正常使用。这个有办法拯救嘛？

**Comment by dylanbai8** [comment]
iOS：Kitsunebi TF版（需要手动修改配置），ShadowRay TF版。

**Comment by 2huYa0** [comment]
实在不知道如何设置，只能再麻烦您帮忙看一下配置了

![EpeAY.jpg](https://s1.ax2x.com/2018/03/11/EpeAY.jpg)

![EpUqi.jpg](https://s1.ax2x.com/2018/03/11/EpUqi.jpg)

**Comment by dylanbai8** [comment]
抱歉，手头没有iOS设备可以帮你做测试。请留言给相关软件的作者咨询一下。
建议 path 处填写 “/” host 处填写 “www.xxx.com” 尝试连接。

**Comment by ntgeralt** [comment]
首先感谢作者制作的一键脚本；
我ios的ShadowRocket能套上作者的一键脚本，首先app要更新到18年1月27日或更新的。
ShadowRocket-混淆进去选择websocket；
路径就留一个斜杠；
最底部内容输入www.4c4ea137-285-4b9e.com你的内容，不是一键脚本显示的/;www.4c4ea137-285-4b9e.com

个人稍微建议，重启和v2ray每日更新作为可选项；

**Comment by 2huYa0** [comment]
感谢作者和楼上的仁兄，按照你们所说的方法，iOS客户端连接正常了，作者或许可以考虑将此方法写入readme。

**Comment by 2huYa0** [comment]
大大，重新运行脚本更新就可以了是吧？VPS需不需要重新安装过系统？

**Comment by dylanbai8** [comment]
可以。

**Comment by 2huYa0** [comment]
报告一个小问题，上一个版本的脚本，在搬瓦工64M的小鸡上可以安装并正常使用，这个新的版本安装会显示“write error (disk full?)”的报错

**Comment by dylanbai8** [comment]
这个报错应该和脚本改动没有关系，重装系统尝试一下。

**Comment by iamhaifeng** [comment]
@2huYa0 请问你在ios上用的哪个客户端呢？我用ShadowRocket 2.1.21 死活不行，PC端可以正常访问，谢谢！

**Comment by 2huYa0** [comment]
我在iOS上用的是Kitsunebi，貌似记得小火箭按照按照完的提示填进去也是没问题的，你看看是不是那里填错了？最近我也没怎么折腾V2Ray了

**Comment by iamhaifeng** [comment]
@2huYa0 我怀疑是iOS9下的ShadowRocket有问题（V2ray+ws+nginx+tls）。

@ntgeralt 请问你的ShadowRocket是在哪个iOS版本上运行正常的呢？环境跟我是一样的吗？

**Comment by 2huYa0** [comment]
@iamhaifeng 非常有可能，可以尝试使用安装了最新版本的固件的机器去试试

**Comment by mojito8327** [comment]
我的设备是IOS 12.3.1，安装了kitsunebi和ShadowRocket，添加了v2ray(ws+tls)kitsunebi可以用，ShadowRocket就不可以。

**Comment by cute-angelia** [comment]
域名证书有问题

**Comment by qzi** [comment]
> 我的设备是IOS 12.3.1，安装了kitsunebi和ShadowRocket，添加了v2ray(ws+tls)kitsunebi可以用，ShadowRocket就不可以。

我也是kitsunebi和电脑上可以用，只有shadowrocket不行

**Comment by keyboard-not-hero** [comment]
IOS设备系统版本12.4.1，shadowrocket可以使用，使用方法步骤：1.混淆选项中选择websocket并填写路径；2.打开TLS，并打开TLS下的允许不安全选项
