### ISSUE TITLE
关于ip限速

### ISSUE THREAD

**Issue by pjomvndy** [dylanbai8/V2Ray_ws-tls_Website_onekey#10]
我搭建的v2ray账号想分享给朋友使用，但考虑到流量问题，想对连接v2ray服务器的ip进行限速，比如单个ip限速300kb/s，请问能做到吗？

**Comment by dylanbai8** [comment]
抱歉，目前实现不了。而且这个issues你发错了地方，请到这里反馈：https://github.com/v2ray/v2ray-core

**Comment by pjomvndy** [comment]
谢谢
