### ISSUE TITLE
小白有个问题…在verifying证书过程中一直请求超时，SSL证书生成失败

### ISSUE THREAD

**Issue by Joeyxworks** [dylanbai8/V2Ray_ws-tls_Website_onekey#11]
换了好几个域名都不行，是let's encrypt的dns延迟吗，用的是文中的免费域名，还请麻烦帮忙解答下，感谢！

**Comment by Joeyxworks** [comment]
原来申请证书是外部服务器发起的啊，之前防火墙没放行端口。。尴尬，再次感谢大佬的脚本！

**Comment by dylanbai8** [comment]
感谢反馈。

**Comment by sjzcook** [comment]
> 原来申请证书是外部服务器发起的啊，之前防火墙没放行端口。。尴尬，再次感谢大佬的脚本！

你好，需要开放那个端口呀？
