### ISSUE TITLE
使用本脚本后成功运行，但我再使用锐速后就不能工作了

### ISSUE THREAD

**Issue by cschongshi** [dylanbai8/V2Ray_ws-tls_Website_onekey#15]
感谢作者，现在使用脚本能够正常运行。但我想使用锐速，发现开启锐速后就不能工作了，但关闭锐速正常，是哪里有冲突吗？该怎么解决？谢谢！

**Comment by dylanbai8** [comment]
冲突。脚本已经自带bbr加速了。无需再安装锐速。

**Comment by cschongshi** [comment]
但我机器是kvm的debian8内核版本是3.16.0-4，使用几条命令也没有看到bbr运行的状态，怎么确定bbr已经在运行呢？还有如果我想卸载bbr转用锐速，改如何操作？谢谢！

**Comment by cschongshi** [comment]
感谢！我再重新安装一下
