### ISSUE TITLE
刚发现v2rayN已经更新到2019.5.15了，现在下载的客户端配置文件已经不能导入了。。。

### ISSUE THREAD

**Issue by eaglepie** [dylanbai8/V2Ray_ws-tls_Website_onekey#40]
刚发现v2rayN已经更新到2019.5.15了，现在下载的客户端配置文件【客户端配置文件下载地址（URL）】已经不能导入了。大佬，能更新一下么？

**Comment by ntgeralt** [comment]
最郁闷的是好像全世界只能用v2rayn一个软件，上面竟然还开始有广告了

**Comment by dylanbai8** [comment]
> 最郁闷的是好像全世界只能用v2rayn一个软件，上面竟然还开始有广告了

https://c2ray.ml/

**Comment by ntgeralt** [comment]
@dylanbai8 多谢分享。试用了下挺好，bat菜单有点多，我想自己弄成四五个bat对应四五个服务器…

**Comment by eaglepie** [comment]
@dylanbai8 谢谢分享！
