### ISSUE TITLE
证书过期了，如何手动更新证书呢？

### ISSUE THREAD

**Issue by eaglepie** [dylanbai8/V2Ray_ws-tls_Website_onekey#47]
如题，输入crontab -e也看到了：
50 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
但是，证书还是过期了。请问一下，如何手动更新证书呢？

**Comment by wulabing** [comment]
服务端关闭 v2ray
执行上面更新证书的语句
开启v2ray 就可以了

eaglepie <notifications@github.com> 于 2019年8月20日周二 19:15写道：
