### ISSUE TITLE
域名dns解析IP 与 本机IP 不匹配

### ISSUE THREAD

**Issue by bolin62007** [dylanbai8/V2Ray_ws-tls_Website_onekey#9]
通过ping域名查看解析出来的ip地址和本机地址是一样的，但是还是停在了域名dns解析IP 与 本机IP 不匹配这里，求助？

**Comment by bolin62007** [comment]
![default](https://user-images.githubusercontent.com/26298490/38302485-71cde8b2-3835-11e8-87d2-b72d7d04a589.png)

**Comment by dylanbai8** [comment]
经过测试不存在问题。脚本也是通过ping来获取域名的dns解析ip的。上图显示脚本没有获取到解析ip ，检查一下是不是域名输入错误了，？

**Comment by dylanbai8** [comment]
安全起见，我把你的反馈截图删除了。感谢反馈！

**Comment by bolin62007** [comment]
谢谢回复，域名在第一步就输入了，就是我ping的那个

**Comment by wulabing** [comment]
昨天看到那张图了。大概是ping的版本问题，可以忽视，比较少见，并且不影响结果

**Comment by bolin62007** [comment]
不懂，实际上就是到这里然后就说ip不匹配
